### PR TITLE
Switch to njump.me

### PR DESCRIPTION
**Pull request by dtonon**
@leo-lox I see you already use njump.me in the bio :)

### CODE REVIEW

**Comment by leo-lox** [comment]
thx for the pr, I checked the og data and see no difference, what is the benefit of using njump.me directly?

**Comment by dtonon** [comment]
As you can see nostr.com already redirects to njump.me, we are switching domain

**Comment by dtonon** [comment]
It's a little expensive :)
https://twitter.com/arcbtc/status/1699146422933741916

**Comment by leo-lox** [comment]
oh, I missed that, thx for letting me know 👍

**Pull request merged**
